### ISSUE TITLE
viewWillDisappear isMovingFromParentViewController

### ISSUE THREAD

**Issue by zalazara** [johnpatrickmorgan/LifecycleHooks#2]
When i check if view.isMovingFromParentViewController always return false.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue. I was able to confirm it when popping a view controller from a `UINavigationController`'s stack. I found that `isMovingFromParentViewController` was `true` within the popped view controller's own`viewWillDisappear(_: )` method, but `false` when the `on(.viewWillDisappear)` hook was run. This seems to be down to timing: the hook is run after the native `viewWillDisappear(_: )`, because it is only run when the `viewWillDisappear(_: )` call is passed on to the child view controllers. This timing discrepancy is an unavoidable limitation of the LifecycleHooks approach. I don't understand why `isMovingFromParentViewController` does not stay `true` until the `parentViewController` is set to `nil`, but that is a facet of UIKit. I'll keep this issue open for a little while in case I find any new information.
